### ISSUE TITLE
cv2.imshow outputs the image incorrectly (blown up)

### ISSUE THREAD

**Issue by zakkarija** [shreelock/gbvs#3]
Matplotlib outputs the saliency map correctly
![Figure_1](https://user-images.githubusercontent.com/44923475/113330149-b763b900-931e-11eb-93fa-b251af68c0ab.png)
however when I output it using 
```cv2.imshow("Output using cv2.imshow",saliency_map_gbvs)```
its outputs is blown out as shown below: 
![Capture](https://user-images.githubusercontent.com/44923475/113330271-d3fff100-931e-11eb-825e-c7b09f13c4cc.PNG)

Is this because of resizing or using incorrect color space?  Any help would be appreciated :)

**Comment by shreelock** [comment]
If you take a look [here](https://github.com/shreelock/gbvs/blob/4c7e3c58e786d053ec4ae6fb9d03bdfeea2c539a/saliency_models/gbvs.py#L92) and the values of the `saliency_map_gbvs`, you will notice that the values have been normalized in a range. 
OpenCV doesn't automatically normalize the values to [0, 255] when trying to imshow, which is why they are differently shown in matplotlib vs imshow.

If you want to use cv2.imshow, you might need to normalize the values again in [0, 255] and then imshow.
