### ISSUE TITLE
Are saliency values of the GBVS model normalized?

### ISSUE THREAD

**Issue by n3urovirtual** [shreelock/gbvs#8]
Hi there, 
I am trying to find the visual saliency of a set of images using the GBVS model (global saliency using `np.average()`, minimum local saliency using `np.min()`, and maximum local saliency using `np.max()`. These 3 numbers are calculated for the `saliency_map_gbvs` array of each image). Doing so, I realized that the range of saliency instead of being between 0 and 255, varies widely from image to image. For example, the minimum saliency can be -0.5 or -0.9 and the maximum can go up to 294 or 275 depending on the image. Why is this happening? This makes a comparison of saliency across images impossible. Is there a way to normalize the values using a 0-1 range (0 for the lowest saliency and 1 for the highest)?

**Comment by shreelock** [comment]
This is happening because of the [cv2.INTER_CUBIC](https://github.com/shreelock/gbvs/blob/4c7e3c58e786d053ec4ae6fb9d03bdfeea2c539a/saliency_models/gbvs.py#L95) interpolation of the result at the end, for resizing the image. This has been the issue with this operation before as well as mentioned [here](https://github.com/opencv/opencv/issues/7195).

You can either `clamp` the values, or do the rescaling as it fits your needs. The resizing is not the part of `gbvs` algorithm, so that is up to you.
