### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by hbrachemi** [shreelock/gbvs#9]
Hi, 
The code works perfectly for most of the images in my dataset. However, it yields this error with few samples, I doubled checked whether there's some problem with the input images, and apparently, this error is only yielded when computing the gbvs.compute_saliency while ittikochneibur.compute_saliency works just fine.
![image](https://user-images.githubusercontent.com/68550699/168878051-284a0e51-d6e4-4cf4-aa9c-eeca0957b5d4.png)

**Comment by shreelock** [comment]
Looks like the error is coming from `graphBasedActivation.calculate(map, activation_sigma)` function from [here](https://github.com/shreelock/gbvs/blob/4c7e3c58e786d053ec4ae6fb9d03bdfeea2c539a/saliency_models/gbvs.py#L71), which eventually calls `markovChain.solve()` throwing an error as we see above. 

Since `map` variable is created from the image [here](https://github.com/shreelock/gbvs/blob/master/saliency_models/gbvs.py#L51), can you please check where are we getting invalid values from?

**Comment by hbrachemi** [comment]
Apparently, the problem comes from the sklearn normalize function, I checked wether the state_transition_matrix variable had any Nan or infinite values and there seems to be none
![image](https://user-images.githubusercontent.com/68550699/168891338-3c1171a3-ebe9-4c1d-afee-aeeced28e2dc.png)

**Comment by shreelock** [comment]
What are the dimensions of the `state_transition_matrix` variable? Can you print it out here? We can run the `normalize` function on it in a python shell, and see if its an sklearn issue, or some edge case

**Comment by hbrachemi** [comment]
looks like (896, 896)

**Comment by shreelock** [comment]
Looks like these would need some in-depth investigation. I am not currently working on this project, so I might be able to get back to you by end of this week when I get some free time. Please feel free to post some other information that you feel might help investigation (dataset, or link to the offending-image)

**Comment by hbrachemi** [comment]
Here's an update,
apparently, the problem comes from the markovChain.solve() and exactly from   v = np.divide(v, sum(v))
and is due to a division by 0. I think adding  a small constant to sum(v) to avoid divisions by 0 would solve the problem
